### ISSUE TITLE
Toolset for windows pratice

### ISSUE THREAD

**Issue by samuelriesz** [sagishahar-zz/lpeworkshop#1]
Hi Sagi Shahar, your work is just amazing! I wonder if you could pack into some zip file all the tools needed to me reproduce the windows labs? It would be great!

**Comment by sagishahar-zz** [comment]
Sorry for the delay @samuelriesz and thanks for your feedback.

I have updated the README.md file to include a link to the Tools directory from the Windows VM as you requested. Enjoy.

**Comment by samuelriesz** [comment]
Hi Satish,

Thank you very much for your kind reply.

When I try to open it, it shows that Google has blocked the document
alerting some kind of term of use violation.

Best regards,
Samuel Riesz


Em ter, 10 de abr de 2018 11:06, @s4gi_ <notifications@github.com> escreveu:
