### ISSUE TITLE
Windows VM for Windows Exercises

### ISSUE THREAD

**Issue by daxin09pp** [sagishahar-zz/lpeworkshop#2]
Could you provide the Windows VM for Windows Exercises? 
Or the test service.
Thank you very much for the exercises.
Thank you very much.

**Comment by tuv7041** [comment]
Any luck with this? Looking for the same thing...

**Comment by sagishahar-zz** [comment]
Thank you for your feedback, it is greatly appreciated.

For licensing reasons the Windows VM cannot be provided. However, I have created a setup script that should work as an alternative on your own VM.

Thank you for your patience, I know it took a while. Life gets in the way at times ;-)
