### ISSUE TITLE
Linux Vuln VM Broken .OVF

### ISSUE THREAD

**Issue by wesgreentree** [sagishahar-zz/lpeworkshop#3]
Hey Sagi, 
Great work here ! Maybe it's an issue only on my end but .OVF gives the error below and can't be imported, I have updated Virtual Box, Downloaded the file twice, and tried VMware Fusion. Can't be this to work, would you double check on your end and perhaps re-up a working VM ?
Props again on the presentation etc !
 
```
Result Code: | VBOX_E_FILE_ERROR (0x80BB0004)
-- | --
Component: | ApplianceWrap
Interface: | IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}
```

**Comment by sagishahar-zz** [comment]
Hi Herbdirty,

The file is an .ova and not an .ovf. I have re-downloaded the file and imported it successfully with VMWare Fusion v8.5.8. If you are using VirtualBox, one potential solution would be to extract the .vmdk file out of the .ova using 7zip or similar, create a new VM, and then point the new VM's hard drive to the extracted vmdk file.

The SHA1 hash of the file is: be0afdf0b3326a55d0763815b757e958d269e36d

Good luck!
